package com.ts.app;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting() + "\n" + (args != null && args.length > 0 ? "args[0]:"+args[0] : "no args"));
    }
}
